# Generated by Django 2.2.5 on 2019-12-16 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStorage',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=16)),
                ('video_file', models.FileField(upload_to='realVideo')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
            ],
        ),
    ]
