# Generated by Django 2.2.5 on 2019-12-24 21:59

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostorage',
            name='video_file',
            field=models.FileField(upload_to=App.models.generate_video_path),
        ),
    ]
