# Generated by Django 2.2.5 on 2019-12-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20191224_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, unique=True)),
                ('user_email', models.CharField(max_length=64, unique=True)),
                ('user_password', models.CharField(max_length=32)),
            ],
        ),
    ]
