# Generated by Django 2.2.5 on 2019-12-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_userinfo_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_admin',
            field=models.BooleanField(default=False, max_length=1),
        ),
    ]
