# Generated by Django 2.2.5 on 2019-12-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_userinfo_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='admin',
            new_name='is_admin',
        ),
    ]
