# Generated by Django 2.2.5 on 2019-12-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20191230_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_admin',
            field=models.BooleanField(default=False, max_length=4, null=True),
        ),
    ]
