# Generated by Django 2.2.5 on 2019-12-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20191230_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_admin',
            field=models.BooleanField(null=True),
        ),
    ]
