# Generated by Django 2.2.5 on 2019-12-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20191230_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
