# Generated by Django 2.2.5 on 2019-12-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20191230_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
